In [342]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_multilabel_classification
from scipy.spatial import distance

In [343]:
l=8
instancias=10
X, Y = make_multilabel_classification(n_samples=instancias, n_features=l, n_classes=5)

In [344]:
X

array([[  6.,   9.,   9.,   2.,   3.,   5.,   8.,   4.],
       [  9.,   9.,   7.,   5.,   4.,   5.,   7.,   6.],
       [  4.,  11.,   7.,   3.,   7.,   6.,   4.,   9.],
       [ 15.,   5.,   1.,   9.,   1.,   9.,   6.,   3.],
       [  4.,  16.,   7.,   2.,   3.,   2.,  10.,   7.],
       [  9.,   7.,   1.,   7.,   3.,   8.,  10.,   3.],
       [  3.,  10.,   6.,   2.,   2.,   3.,  10.,   8.],
       [  3.,  15.,   9.,   6.,   9.,   1.,   6.,  10.],
       [ 14.,   8.,   4.,   4.,   8.,   3.,  10.,  10.],
       [  9.,  13.,   3.,   6.,   4.,   8.,   9.,   2.]])

In [345]:
Y

array([[0, 0, 1, 0, 1],
       [0, 1, 1, 1, 1],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1]])

In [414]:
from random import randint
RndDimensions=np.random.randint(0, 2,l)
RndDimensions=RndDimensions.astype(bool)
RndDimensions

array([ True,  True, False, False, False,  True, False, False], dtype=bool)

In [413]:
from random import shuffle
s=list(range(instancias))
random.shuffle(s)
RndNeighbors=np.array(s[:(int(len(s)/2))])
RndNeighbors

array([3, 6, 2, 4, 8])

In [415]:
filtro = np.array([True, False, True, False, False, False, False, False])
X[:, RndDimensions]

array([[  6.,   9.,   5.],
       [  9.,   9.,   5.],
       [  4.,  11.,   6.],
       [ 15.,   5.,   9.],
       [  4.,  16.,   2.],
       [  9.,   7.,   8.],
       [  3.,  10.,   3.],
       [  3.,  15.,   1.],
       [ 14.,   8.,   3.],
       [  9.,  13.,   8.]])

In [355]:
for i in RndNeighbors:
    print(distance.euclidean(X[i,:],RndDimensions))
    #print(X[i,:])

18.49324200890693
18.894443627691185
20.8806130178211
21.142374511865974
23.259406699226016
