In [1]:
from sklearn.datasets import make_multilabel_classification
import numpy as np

from sklearn.disturbing_neighbors import disturbing_neighbors
from sklearn.ensemble import bagging
from sklearn.ensemble import BaggingClassifier

In [2]:
for i in range(2):
    print('prueba:', i + 1)
    np.random.seed(0)
    X,Y=make_multilabel_classification(n_samples=12, n_features=10) 
    print(X,Y)
    np.random.seed(1)
    X,Y=make_multilabel_classification(n_samples=12, n_features=10) 
    print(X,Y)

prueba: 1
[[  7.   8.   1.   9.   1.   9.   7.   3.   0.   4.]
 [  8.   5.   4.   8.   3.   7.  11.   5.   5.   4.]
 [  5.   8.   9.   4.   7.   3.   4.   5.   1.   6.]
 [  6.   7.   4.   4.   6.   4.   3.   4.   4.  13.]
 [  6.   4.   1.  10.   2.   2.   5.   4.   1.   0.]
 [  4.   3.   4.   3.   9.   3.   6.   4.   1.   9.]
 [  8.   8.   3.  15.   3.   2.   8.   3.   3.  10.]
 [  8.   4.   6.  12.   4.  11.   6.   3.   2.   9.]
 [  8.   3.   8.   3.   8.   2.   8.   3.   3.  11.]
 [  8.   3.   5.   4.   4.   3.   6.   4.   1.   9.]
 [ 12.   6.   2.  12.   6.   3.   7.   2.   4.   3.]
 [  7.   8.   6.   6.   1.   2.   8.   1.   5.   1.]] [[0 1 0 0 0]
 [0 1 1 1 1]
 [0 0 1 0 0]
 [1 0 1 0 0]
 [1 1 0 0 0]
 [0 0 1 0 0]
 [1 1 0 0 0]
 [0 1 1 0 0]
 [0 0 1 0 1]
 [0 0 1 0 0]
 [1 1 1 1 0]
 [0 0 0 1 0]]
[[  6.   5.   7.   2.   5.   2.   5.  10.   5.   4.]
 [  5.   9.   1.   6.   0.   0.   5.   5.   8.   7.]
 [  2.   4.   6.   6.   7.   2.   3.   8.   5.   0.]
 [  5.   2.   9.   7.   5.  11.   6. 

In [22]:
dn=disturbing_neighbors()
#dn=bagging()
dn=BaggingClassifier()
matrizFitX = np.matrix([X[i,:] for i in range(5)], dtype=int)
matrizFitY = np.matrix([Y[i,:] for i in range(5)], dtype=int)
#dn.fit(matrizFitX,matrizFitY)

TypeError: 'module' object is not callable

In [51]:
MAX_INT = np.iinfo(np.int32).max
np.random.rand()

0.8763891522960383